### ISSUE TITLE
Bug in as.mids2

### ISSUE THREAD

**Issue by MauricioCoronel** [stefvanbuuren/mice#39]
Hello. I have encountered an error when converting a dataframe into a mice mids and then back-converted the mice mids into a new R data frame. The data produces different datasets. 
I found this error on my own data, and reproduced it using a built-in dataset (epi, from the psych package).
Below is the syntax I used to reproduce the bug. 
Thanks.

[Imputed example.txt](https://github.com/stefvanbuuren/mice/files/1027428/Imputed.example.txt)

**Comment by stefvanbuuren** [comment]
Hi thanks. The `as.mids2()` function was as a temporary fixup created long ago. I have added several fixups, and was therefore wondering whether you get the same behaviour of the `as.mids()` function in a recent version of `mice`. 
Stef.

**Comment by MauricioCoronel** [comment]
We have found the same issue using either function. I posted the code using as.mids2 because I had understood it was an "updated" fix, but even with as.mids the same issue is happening. 
Thanks for your response.

**Comment by stefvanbuuren** [comment]
I am not able to run your example since it seems to require `SPSS`. At some point, there is a hard-coded file `C:/FILEPATH.sav`, which is don't have. I cannot see what the nature of the problem is.

Is your finding perhaps related to exporting to and importing from `SPSS`, rather than being an `as.mids()` problem? There is a function in `mice` called `mids2spss()` that is meant to export `mids` objects to `SPSS`.

**Comment by MauricioCoronel** [comment]
I apologize that the example cannot be ran without creating the SPSS file from the .sps document. The FILEPATH location should be pointing to the SPSS file (which should be your working directory).

The following syntax should skip the SPSS file creation altogether.
Thank you.

#Built-in package used is epi, from the psych package
HSIY2014 <- epi
summary(HSIY2014)

#Impute using mice
set.seed(20170327) 
predictormatrix <- quickpred(HSIY2014,exclude="id",method="spearman",mincor=0.1,minpuc=0.5)
HSIY2014_imp <- mice(HSIY2014,m=5,predictorMatrix=predictormatrix) 
HSIY2014_ImputedData<-complete(HSIY2014_imp,action="long",include=TRUE)

# convert dataframe to mids object using as.mids
HSIY2014_mids<-as.mids(HSIY2014_ImputedData)  

# and back to a data frame, so we can compare the two datasets and make sure nothing went wrong 
HSIY2014_imp_R_2 <- complete(HSIY2014_mids, action="long",include=TRUE)

# Get a summary before mids
table(HSIY2014_ImputedData$V53)
#    1     2 
# 8830 12496 

# Get a summary after mids
table(HSIY2014_imp_R_2$V53)
#    1     2 
#10273 14529 

#Inconsistency found between these datasets

**Comment by stefvanbuuren** [comment]
That's curious. In `mice 2.36` running your code gives me identical counts. Which version of `mice` produces this, and on what platform?
[reproduce.pdf](https://github.com/stefvanbuuren/mice/files/1046734/reproduce.pdf)

**Comment by MauricioCoronel** [comment]
We have been running version 2.30 (on windows 10, if that helps).  When installing/updating the package there is no indication of version 2.36, so perhaps this might have been addressed in the updated version and we are just not caught up for some reason.

**Comment by stefvanbuuren** [comment]
OK thanks. mice 2.30 is the latest on CRAN. It appears that current version of `as.mids()` works as expected. I am going to close, but please let me know if problem persist. Stef.
